"""Vector store implementation using ChromaDB.

Provides semantic search capabilities for memories using embeddings
generated by sentence-transformers.
"""

import logging
from pathlib import Path
from typing import List, Optional

from oxmemory.core.models import Memory, MemoryType
from oxmemory.core.config import get_brain_path, load_config

logger = logging.getLogger(__name__)

# Store directory within .0xmemory
VECTOR_STORE_DIR = ".store/chroma"

# Default embedding model
DEFAULT_EMBEDDING_MODEL = "all-MiniLM-L6-v2"


class VectorStore:
    """Vector store for semantic memory search.
    
    Uses ChromaDB for vector storage and sentence-transformers
    for generating embeddings locally.
    """
    
    def __init__(
        self, 
        project_dir: Optional[Path] = None,
        embedding_model: Optional[str] = None,
    ):
        """Initialize the vector store.
        
        Args:
            project_dir: Project directory. Defaults to current directory.
            embedding_model: Sentence-transformers model name.
        """
        self.project_dir = Path(project_dir) if project_dir else Path.cwd()
        self.brain_path = get_brain_path(self.project_dir)
        self.store_path = self.brain_path / VECTOR_STORE_DIR
        
        # Determine embedding model
        self.embedding_model = embedding_model
        if self.embedding_model is None:
            try:
                config = load_config(self.project_dir)
                self.embedding_model = config.embeddings.model
            except FileNotFoundError:
                self.embedding_model = DEFAULT_EMBEDDING_MODEL
        
        # Lazy-loaded components
        self._client = None
        self._collection = None
        self._embedder = None
    
    @property
    def client(self):
        """Lazy-load ChromaDB client."""
        if self._client is None:
            import chromadb
            from chromadb.config import Settings
            
            # Ensure store directory exists
            self.store_path.mkdir(parents=True, exist_ok=True)
            
            self._client = chromadb.PersistentClient(
                path=str(self.store_path),
                settings=Settings(
                    anonymized_telemetry=False,
                    allow_reset=True,
                ),
            )
        return self._client
    
    @property
    def collection(self):
        """Get or create the memories collection."""
        if self._collection is None:
            self._collection = self.client.get_or_create_collection(
                name="memories",
                metadata={"description": "0xMemory stored memories"},
            )
        return self._collection
    
    @property
    def embedder(self):
        """Lazy-load sentence-transformers model."""
        if self._embedder is None:
            from sentence_transformers import SentenceTransformer
            
            logger.info(f"Loading embedding model: {self.embedding_model}")
            self._embedder = SentenceTransformer(self.embedding_model)
        return self._embedder
    
    def _embed(self, texts: List[str]) -> List[List[float]]:
        """Generate embeddings for texts.
        
        Args:
            texts: List of texts to embed.
            
        Returns:
            List of embedding vectors.
        """
        embeddings = self.embedder.encode(texts, convert_to_numpy=True)
        return embeddings.tolist()
    
    def _memory_to_metadata(self, memory: Memory) -> dict:
        """Convert memory fields to ChromaDB metadata."""
        return {
            "type": memory.type.value,
            "tags": ",".join(memory.tags) if memory.tags else "",
            "source": memory.source,
            "salience": memory.salience,
            "created_at": memory.created_at.isoformat(),
        }
    
    def _metadata_to_memory_filter(
        self,
        memory_types: Optional[List[MemoryType]] = None,
    ) -> Optional[dict]:
        """Build ChromaDB where filter from memory types."""
        if not memory_types:
            return None
        
        if len(memory_types) == 1:
            return {"type": memory_types[0].value}
        
        return {
            "$or": [{"type": mt.value} for mt in memory_types]
        }
    
    # -------------------------------------------------------------------------
    # CRUD Operations
    # -------------------------------------------------------------------------
    
    def add(self, memory: Memory) -> None:
        """Add a memory to the vector store.
        
        Args:
            memory: Memory to add.
        """
        embedding = self._embed([memory.content])[0]
        
        self.collection.add(
            ids=[memory.id],
            embeddings=[embedding],
            documents=[memory.content],
            metadatas=[self._memory_to_metadata(memory)],
        )
    
    def add_many(self, memories: List[Memory]) -> None:
        """Add multiple memories to the vector store.
        
        Args:
            memories: List of memories to add.
        """
        if not memories:
            return
        
        contents = [m.content for m in memories]
        embeddings = self._embed(contents)
        
        self.collection.add(
            ids=[m.id for m in memories],
            embeddings=embeddings,
            documents=contents,
            metadatas=[self._memory_to_metadata(m) for m in memories],
        )
    
    def delete(self, memory_id: str) -> bool:
        """Delete a memory from the vector store.
        
        Args:
            memory_id: Memory ID to delete.
            
        Returns:
            True if deleted (always returns True for now).
        """
        try:
            self.collection.delete(ids=[memory_id])
            return True
        except Exception:
            return False
    
    def get(self, memory_id: str) -> Optional[dict]:
        """Get a memory by ID.
        
        Args:
            memory_id: Memory ID.
            
        Returns:
            Memory data dict if found, None otherwise.
        """
        result = self.collection.get(ids=[memory_id])
        
        if result["ids"]:
            return {
                "id": result["ids"][0],
                "content": result["documents"][0] if result["documents"] else "",
                "metadata": result["metadatas"][0] if result["metadatas"] else {},
            }
        return None
    
    def search(
        self,
        query: str,
        limit: int = 5,
        memory_types: Optional[List[MemoryType]] = None,
    ) -> List[dict]:
        """Semantic search for memories.
        
        Args:
            query: Search query.
            limit: Maximum number of results.
            memory_types: Filter by memory types.
            
        Returns:
            List of matching memory dicts with distances.
        """
        query_embedding = self._embed([query])[0]
        
        where_filter = self._metadata_to_memory_filter(memory_types)
        
        results = self.collection.query(
            query_embeddings=[query_embedding],
            n_results=limit,
            where=where_filter,
        )
        
        memories = []
        if results["ids"] and results["ids"][0]:
            for i, memory_id in enumerate(results["ids"][0]):
                memories.append({
                    "id": memory_id,
                    "content": results["documents"][0][i] if results["documents"] else "",
                    "metadata": results["metadatas"][0][i] if results["metadatas"] else {},
                    "distance": results["distances"][0][i] if results["distances"] else 0,
                })
        
        return memories
    
    # -------------------------------------------------------------------------
    # Maintenance
    # -------------------------------------------------------------------------
    
    def count(self) -> int:
        """Get the number of memories in the vector store.
        
        Returns:
            Number of stored memories.
        """
        return self.collection.count()
    
    def clear(self) -> None:
        """Clear all memories from the vector store."""
        self.client.delete_collection("memories")
        self._collection = None
    
    def rebuild_from_memories(self, memories: List[Memory]) -> int:
        """Rebuild the vector store from a list of memories.
        
        Clears existing data and reindexes all memories.
        
        Args:
            memories: List of memories to index.
            
        Returns:
            Number of memories indexed.
        """
        # Clear existing
        self.clear()
        
        # Add all memories
        if memories:
            self.add_many(memories)
        
        return len(memories)
    
    def get_all_ids(self) -> List[str]:
        """Get all memory IDs in the vector store.
        
        Returns:
            List of memory IDs.
        """
        result = self.collection.get()
        return result["ids"] if result["ids"] else []
